from setuptools import setup, find_packages

setup(
    name='wsgissi',
    version='0.7',
    url='https://github.com/baverman/wsgissi/',
    license='MIT',
    author='Anton Bobrov',
    author_email='baverman@gmail.com',
    description='WSGI middleware to process nginx compatible ssi',
    long_description=open('README.rst').read(),
    py_modules=['wsgissi'],
    install_requires=['WebOb>=1.4'],
    include_package_data=True,
    zip_safe=False,
    platforms='any',
    classifiers=[
        'Development Status :: 4 - Beta',
        # 'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Intended Audience :: Information Technology',
        'Intended Audience :: System Administrators',
        'License :: OSI Approved :: MIT License',
        'Operating System :: POSIX',
        'Operating System :: MacOS',
        'Operating System :: Unix',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Internet',
        'Topic :: Scientific/Engineering',
        'Topic :: System :: Distributed Computing',
        'Topic :: System :: Systems Administration',
        'Topic :: System :: Monitoring',
    ]
)
